- id: doi:10.1038/s41597-021-00863-5
  image: images/publications/chest_xray_dataset.PNG
  tags:
    - multimodal learning
    - eye-tracking
    - medical imaging
- id: doi:10.1145/3404835.3462959
  image: images/publications/DeepQAMVS.PNG
  tags:
    - multimodal learning
    - video summarization
    - video understanding
- id: doi:10.1007/978-3-030-87240-3_77
  image: images/publications/anaxnet.PNG
  tags:
    - scene-graphs
    - medical imaging
- id: doi:10.1145/3459637.3481950
  title: "SAUCE: Truncated Sparse Document Signature Bit-Vectors for Fast Web-Scale Corpus Expansion"
  image: images/publications/sauce.PNG
  tags:
    - information retrieval
- id: doi:10.1111/mice.12812
  image: images/publications/SHM.PNG
- id: doi:10.48550/arXiv.2108.00316
  image: images/publications/chest_imagenome.PNG
  tags:
    - multimodal learning
    - scene-graphs
    - medical imaging
- id: doi:10.48550/arXiv.2204.10314
  image: images/publications/swaro.PNG
  tags:
    - contrastive learning
    - self-supervised learning
    - adversarial attacks
    - robust representations
- id: doi:10.48550/arXiv.2206.01197
  image: images/publications/hard_negative.PNG
  tags:
    - contrastive learning
    - self-supervised learning
- id: doi:10.1109/APR59189.2023.00009
  image: images/publications/fixeval.PNG
  tags:
    - code repair
    - natural language processing
- id: doi:10.1145/3529190.3529222
  image: images/publications/data_quality.PNG
  tags:
    - data quality
- id: doi:10.1007/978-3-031-16431-6_55
  publisher: Medical Image Computing and Computer Assisted Intervention (MICCAI)
  image: images/publications/CheXRelNet.PNG
  tags:
    - scene-graphs
    - medical imaging
- id: doi:10.1016/j.ymssp.2022.109910
  image: images/publications/SHM.PNG
- id: doi:10.1109/BigData55660.2022.10020861
  image: images/publications/PRIED.PNG
  tags: 
  - privacy-preserving ML
- id: doi:10.48550/arXiv.2302.04865
  publisher: IEEE/CVF Winter Conference on Applications of Computer Vision (WACV)
  date: '2025-01-04'
  image: images/publications/ELBA.PNG
  tags: 
  - multimodal learning
  - embodied AI
- id: doi:10.1145/3653703
  image: images/publications/CSCW.PNG
  tags:
    - social media
    - natural language processing
- id: doi:10.1109/ICASSP48485.2024.10446342
  image: images/publications/UAMIXMAE.PNG
  tags:
    - contrastive learning
    - self-supervised learning
    - audio understanding
- id: doi:10.1609/aaai.v38i3.27989
  image: images/publications/CORONET.PNG
  tags:
    - multimodal learning
    - video localization
    - video understanding
- id: doi:10.1371/journal.pdig.0000205
  image: images/publications/AIHealth.PNG
  tags:
    - editorial
    - AI in healthcare
- id: doi:10.1145/3543507.3583514
  tags:
    - social media
    - natural language processing
- id: doi:10.1016/j.ebiom.2023.104525
  image: images/publications/AIHealth.PNG
  tags:
    - editorial
    - AI in healthcare
- id: doi:10.1007/978-3-031-43849-3_22
  image: images/publications/MGCN.PNG
  publisher: International Conference on Theory and Practice of Digital Libraries (TPDL)
  date: '2023-09-22'
  tags:
    - text representations
    - natural language processing
- id: doi:10.1145/3583780.3615485
  image: images/publications/MARBLE.PNG
  tags:
    - entity extraction
    - model selection
    - natural language processing
- id: doi:10.1007/978-3-031-43904-9_66
  publisher: Medical Image Computing and Computer Assisted Intervention (MICCAI)
  image: images/publications/CheXRelFormer.PNG
  tags:
    - medical imaging
- id: doi:10.1145/3583780.3615485
  title: Fine-Grained Alignment for Cross-Modal Recipe Retrieval
  authors:
  - Muntasir Wahed
  - Xiaona Zhou
  - Tianjiao Yu
  - Ismini Lourentzou
  publisher: IEEE/CVF Winter Conference on Applications of Computer Vision (WACV)
  date: '2024-01-04'
  image: images/publications/FARM.PNG
  tags: 
  - multimodal learning
  - contrastive learning
  - robust representations
  link: https://openaccess.thecvf.com/content/WACV2024/papers/Wahed_Fine-Grained_Alignment_for_Cross-Modal_Recipe_Retrieval_WACV_2024_paper.pdf
