name: Fetch Members

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update_research:
    name: Fetch Conferences
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install packages
        run: python -m pip install --upgrade --requirement ./fetch-members/requirements.txt
      - name: Fetch conferences
        run: python ./fetch-members/fetch-members.py
      - name: Commit updated members
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "_members/*.md"
          commit_message: "Fetch members"
          push_options: --force
